### ISSUE TITLE
Unknown Method create() when syncing Shopify products over tunnel

### ISSUE THREAD

**Issue by jimmerk** [craftcms/shopify#67]
### Description
We're getting the follow error when syncing Shopify products over a tunnel. We've tried this with both ddev/ngrok and cloudflare tunnels. Tunnels are otherwise working fine. We also tried reinstalling the Shopify plugin.  

`yii\base\UnknownMethodException: Calling unknown method: craft\shopify\records\ProductData::create() in /var/www/html/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /var/www/html/vendor/craftcms/shopify/src/services/Products.php(129): yii\base\Component->__call('create', Array)
#1 /var/www/html/vendor/craftcms/shopify/src/services/Products.php(63): craft\shopify\services\Products->createOrUpdateProduct(Object(Shopify\Rest\Admin2022_10\Product), Array)
#2 /var/www/html/vendor/craftcms/shopify/src/controllers/ProductsController.php(48): craft\shopify\services\Products->syncAllProducts()
#3 [internal function]: craft\shopify\controllers\ProductsController->actionSync()
#4 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('sync', Array)
#7 /var/www/html/vendor/craftcms/cms/src/web/Application.php(302): yii\base\Module->runAction('shopify/product...', Array)
#8 /var/www/html/vendor/craftcms/cms/src/web/Application.php(627): craft\web\Application->runAction('shopify/product...', Array)
#9 /var/www/html/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /var/www/html/web/index.php(12): yii\base\Application->run()
#12 {main}`

### Steps to reproduce

1. ddev start & start cloudflare or ngrok tunnel
2. Utilities > Shopify > Sync Products

### Additional info

- Craft version: 4.4.11
- PHP version: 8.1.18
- Database driver & version: mysql 
- Plugins & versions: Shopify 3.1.0

**Comment by jimmerk** [comment]
After moving to Shopify 3.1.1, deleting vendor folder, and updating composer, all is well. Webhooks are working! 

Thanks Luke!
